<?php $_product = $this->getProduct();?>
<?php $buttonTitle = $this->__('Add to Cart'); Mage::helper("TimeLock/TimeChecker")?>
<?php
/** @var OAV_TimeLock_Helper_TimeChecker $timeCheckerHelper */
$timeCheckerHelper = Mage::helper("TimeLock/TimeChecker");
?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
            <label for="qty"><?php echo $this->__('Qty:') ?></label>
            <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Qty')) ?>" class="input-text qty" />
        <?php endif; ?>
        <?php if($timeCheckerHelper->isProductLock($_product)): ?>
            <span><?php echo sprintf('Locked %s', $timeCheckerHelper->getTimeLockInterval()) ?></span>
        <?php else: ?>
            <button type="button" title="<?php echo $buttonTitle ?>" id="product-addtocart-button" class="button btn-cart" onclick="productAddToCartForm.submit(this)">
                <span><span><?php echo $buttonTitle ?></span></span>
            </button>
        <?php endif ?>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>